### ISSUE TITLE
C# executable gives error

### ISSUE THREAD

**Issue by harewei** [Microsoft/CNTK#1188]
I'm using the "EvalClients.sln" for building the C# application.  If I run it in Visual Studio everything works fine, but the .exe file produced (for both debug or release x64) will give an error when I run it at line 
`using (var model = new IEvaluateModelManagedF())`

giving error
`CallStack:    於 Microsoft.MSR.CNTK.GetEval<float>(IEvaluateModel<float>** )
   at Microsoft.MSR.CNTK.Extensibility.Managed.IEvaluateModelManaged<float>..ctor(String funcName)
   at Microsoft.MSR.CNTK.Extensibility.Managed.CSEvalClient.Program.Evaluate() 於 c:\Users\Andy \Documents\Visual Studio 2013\Projects\Examples\Evaluation\CSEvalClient\Program.cs: line 542
 Inner Exception: No Inner Exception`

**Comment by zhouwangzw** [comment]
The .exe file requires some dlls which are usually available under the same directory as .exe, .e.g. $(SolutionDir)\CSEvalClient.Debug|Release. If you start the .exe from another directory, these dlls should be searchable, e.g. as a part of PATH environment variable. Could this be the reason causing the error?

**Comment by harewei** [comment]
I ran the .exe at the place where it's generated.
the EvaClient.sln exists in C:\Users\Andy\Documents\Visual Studio 2013\Projects\Examples\Evaluation
the final .exe is at C:\Users\Andy\Documents\Visual Studio 2013\Projects\Examples\Evaluation\CSEvalClient\obj\x64\Release, which is the default location after building the solution

Two things to note, I removed the two CPP projects that were in EvaClient.sln before, but they shouldn't affect me since I'm not doing anything with C++.  Another is running the .exe gave an error regarding EvalWrapper.dll, but then I copied the file from C:\Users\Andy\Documents\Visual Studio 2013\Projects\Examples\Evaluation\packages\Microsoft.Research.CNTK.CpuEval-mkl.2.0-beta3\lib\net45\x64 to the release folder, which got rid of the error (the callstack error is still present though).

**Comment by zhouwangzw** [comment]
Usually the following dlls are copied to the .exe directory when you build your applicaiton using Nuget package: evaldll.dll, EvalWrapper.dll, liiomp5md.dll, Math.dll, and mkl_cntk_p.dll. They are needed to run the application, as decribed [here](https://github.com/Microsoft/CNTK/wiki/EvalDLL-Evaluation-on-Windows#shipping-evaldlllibrary-with-your-windows-application). Could you please check whether you have these dlls available in the .exe directory?
I just tried to remove all C++ projects and built the only CSEvalClient project from CsEvalClient.sln. I can see all these dlls in the .exe directory. If you still have problems, you might want to uninstall the Nuget package and reinstall it again. We have just published the latest Nuget Package 2.0-Beta7.
Thanks

**Comment by harewei** [comment]
Strange, my .exe directory does not contain the files you listed even after I rebuild the solution.  If I copy them directly from C:\local\cntk\cntk to the .exe directory, the same error still occurs.  I also tried to add the DLL to my solution "References", but says they can not be added.

I have the 2.0 beta 7 nuget package installed.
[xzxz.png](https://postimg.org/image/673xrrcw9/)

**Comment by zhouwangzw** [comment]
@harewei Unfortunately I was unable to repo your issues with the Beta 7 binary and Nuget package. For further investigation, could you please try a couple of things:
1) Are you able to run the Examples/Evaluation/EvalClients.sln contained in the [Beta 7 CPU binary download package](CNTK for Windows v.2.0 Beta 7 CPU only) without any modification?
2) Are you building your own application using X64 as platform? It seems yes from the directory name you described. Could you please have a double check?
3) If possible, could you please send me the solution file (.sln), the project file (.csproj) as well as the files in the "packages" directory which is in the same directory as .sln, in particular the file with name "packages\Microsoft.Research.CNTK.CpuEval-mkl.2.0-beta7\build\net45\Microsoft.Research.CNTK.CpuEval-mkl.targets"? Or it is even better that you can send me a repo package, for example, using program.cs in examples/evaluation/CSEvalClient.

Thanks,

**Comment by harewei** [comment]
It turns out that the correct .exe generated is actually at C:\local\cntk\x64\CSEvalClient.Release
whereas before I thought it the one in C:\local\cntk\Examples\Evaluation\CSEvalClient

Issue has now been resolved
