### ISSUE TITLE
confusing behavior in MinibatchSourceFromData.next_minibatch

### ISSUE THREAD

**Issue by Alan-Lee123** [Microsoft/CNTK#2214]
I am confused the behavior of function **_MinibatchSourceFromData.next_minibatch_** in [this file](https://github.com/Microsoft/CNTK/blob/master/bindings/python/cntk/io/__init__.py) when the data is sequence.
In line 699-708:
```
while end < self._num_samples: 
            new_num_samples = { name: actual_num_samples[name] + (MinibatchSourceFromData._get_len(value[end]) if self._is_sequence[name] else 1)
                                for name, value in self._data.items() }
            # return up to requested number of samples. but at least one even if longer
            # also stop if we hit the maximum requested number of samples
            max_num_samples = max(new_num_samples.values())
            if actual_num_samples and (max_num_samples > num_samples or self._total_num_samples + max_num_samples > self._max_samples):
                break
            actual_num_samples = new_num_samples
            end += 1
```
If the length of the first value of _self_.__data_ is bigger than _num_samples_, the loop will break with _end_ equals 0.

And then, in line 728, _mb_data_ will be **[]**
```
mb_data = arg[begin+worker_rank:end+worker_rank:number_of_workers]
```
At last, in line 735, _mb_data_ will cause an error since it is empty.
```
value = Value.create(self._vars[si.name], mb_data)
```
The **error** is 
```
File "C:\Users\*\Anaconda3\lib\site-packages\cntk\io\__init__.py", line 728, in next_minibatch
    value = Value.create(self._vars[si.name], mb_data)
  File "C:\Users\*\Anaconda3\lib\site-packages\cntk\internal\swig_helper.py", line 69, in wrapper    result = f(*args, **kwds)
  File "C:\Users\*\Anaconda3\lib\site-packages\cntk\core.py", line 466, in create
    True)  # always create a copy in Value
```

Besides, why does the length of the sequence need to be counted? If my data are 10000 sentences whose lengths are around 100, why should calling _next_minibatch(100)_ return 1 sentence rather than 100 sentences? I am confused about it.

**Comment by meijiesky** [comment]
CNTK text-format reader reads text-based files in its unique way. Please refer to tutorial 204 and the link below.

[https://docs.microsoft.com/en-us/cognitive-toolkit/brainscript-minibatchsize-and-python-minibatch_size_in_samples-in-cntk](url)

Wish this could help.

**Comment by Alan-Lee123** [comment]
@meijiesky Thank you very much. This link perfectly answers my question.
By the way, the crash problem I mentioned above still exists when one sequence length is bigger than the minibatch size.

**Comment by eldakms** [comment]
This is a bug and it should be fixed.

**Comment by alexpolozov** [comment]
I'm getting an error ` The number of sequences must be > 0` pretty much on every possible way I'm trying to test my model. It takes as input a variable-length sequence. In the test set, no sequence is longer than the minibatch size.

The approximate code is smth like
``` python
train_streams = dict(x=(train_data[0], C.layers.typing.Sequence[C.layers.typing.tensor]),
                     y=np.array(train_data[1], dtype=np.float32))
train_source = C.io.MinibatchSourceFromData(train_streams)
for epoch in range(args.max_epochs):
   # Training code here... have to iterate over the data manually because `loss.train()` causes the same exception

   test_streams = dict(x=(test_data[0], C.layers.typing.Sequence[C.layers.typing.tensor]),
                       y=np.array(test_data[1], dtype=np.float32))
   test_source = C.io.MinibatchSourceFromData(test_streams, max_samples=len(test_data[0]))
   loss.test(test_source, minibatch_size=args.batch_size,
             model_inputs_to_streams={x: test_source.streams.x, golden: test_source.streams.y},
             callbacks=[progress])
```

@eldakms do you think this is the same issue? If so, how can I set up training & testing with variable-length sequences? The link above doesn't really answer it.

**Comment by eldakms** [comment]
Yes. The default behavior of built-in minibatch sources should be (and it is for all C++ built-in mbsources) - if the first sequence longer than the minibatch size, it should still be added to the minibatch data. Sorry. I will reprioritize/reassign this. Should be fixed soon.

**Comment by alexpolozov** [comment]
However, all my sequences are _smaller_ than the minibatch size, and I'm still getting this error.
