### ISSUE TITLE
Empty __init.py__ file leads to import errors in Detection Demo of FastRCNN

### ISSUE THREAD

**Issue by hellosaumil** [Microsoft/CNTK#2705]
Under `/Examples/Image/Detection` directory `__init.py__` is an empty file which leads to import errors while running `DemoDetection.py` and/or `run_fast_rcnn.py`.

**Comment by hellosaumil** [comment]
I get errors as `ImportError: No module named 'utils.od_utils'` when running codes.

**Comment by KeDengMS** [comment]
Can you try add it to PYTHONPATH?

**Comment by hellosaumil** [comment]
@KeDengMS I tried adding path `'my-path/Examples/Image/Detection/'` to `PYTHONPATH` and exported it.

Yet, I get the following error : 
1. `ImportError: No module named 'utils.cython_modules.cpu_nms'` while running `DetectionDemo.py`
2. `ImportError: No module named 'cython_modules.cython_bbox'` while running `run_fast_rcnn.py`

**Comment by spandantiwari** [comment]
You should add this to PYTHONPATH:
Examples/Image/Detection/utils/cython_modules

**Comment by hellosaumil** [comment]
I tried adding cython_modules as already mentioned above. 

But get following error: `ImportError: No module named 'utils.cython_modules.cpu_nms'`

**Comment by spandantiwari** [comment]
You mentioned that you added 'my-path/Examples/Image/Detection/'. Did you try adding Examples/Image/Detection/utils/cython_modules?

Also, what's your platform and Python version? We have pre-built modules for Python 3.5 for Windows and for Python 3.4, 3.5, 3.6 for Linux. If you specs are different, then you will have to build these modules yourself.

**Comment by hellosaumil** [comment]
@spandantiwari I tried all the possible permutations.

I'm running docker cntk-2.3-cpu-py36 image on MacOS. I also tried this process on AWS EC2.

**Comment by hellosaumil** [comment]
@KeDengMS @spandantiwari 

I was able to solve this problem by doing 2 things:

1. Add `'my-path/Examples/Image/Detection/'` to `PYTHONPATH`
2. Rename files under cython_modules as
         2.1 `cpu_nms.cpython-35m.so` as `cpu_nms.cpython-35m.so`
         2.2 `cython_bbox.cpython-35m.so` as `cython_bbox.so`

Note: One should rename files with `cpython-3Xm` based on their version of python; where 3X is 36 for python3.6 and 35 for python3.5.

Hope this helps.

**Comment by bartkowiaktomasz** [comment]
@hellosaumil 
How did you manage to solve the issue with:
_ImportError: No module named 'utils.rpn'_
Did you just add the directory to PYTHONPATH? 
I have tried adding:
`export PYTHONPATH="$PYTHONPATH:/home/<path>/Detection/"`
to `~/.bashrc`
but it does not seem to work.

**Comment by hellosaumil** [comment]
@bartkowiaktomasz After adding it to `~/.bashrc`, did you source that file like, `source ~/.bashrc` or try running it in new tab/window? If not, then please do so.

If it still doesn't work, what the version of your CNTK?

**Comment by bartkowiaktomasz** [comment]
@hellosaumil Creating `__init__.py` in `utils` helped! Thank you!
Btw. I though the issue with creating empty init files was resolved in earlier versions of Python (I'm using 3.5).

**Comment by devedse** [comment]
I've tried changing file names and things like that but keep running into random errors like stated above:

![image](https://user-images.githubusercontent.com/2350015/39880063-df1dbf56-547c-11e8-803e-d2ea5f9f7ae5.png)

![image](https://user-images.githubusercontent.com/2350015/39880098-fb85599c-547c-11e8-9619-7a52f8be773d.png)

When I change even more filenames the issue doesn't get better

![image](https://user-images.githubusercontent.com/2350015/39880110-065ce8a8-547d-11e8-8a87-703cb6870a11.png)

![image](https://user-images.githubusercontent.com/2350015/39880041-cf44f2fc-547c-11e8-9c12-96d5521443ce.png)

Any ideas?

**Comment by spandantiwari** [comment]
@devedse You need to set the PYTHONPATH varibale to (also) point at the folder with cython modules. Something like: 
`set PYTHONPATH=E:\cntk\Examples\Image\Detection\utils\cython_modules;%PYTHONPATH%`

**Comment by devedse** [comment]
@spandantiwari I got it configured like this:
![image](https://user-images.githubusercontent.com/2350015/39928381-7cef09c0-5535-11e8-8a98-8d662c9cf909.png)

But still see this error:
![image](https://user-images.githubusercontent.com/2350015/39928427-9a840c06-5535-11e8-947b-2aa18b25d7fa.png)

**Comment by spandantiwari** [comment]
My guess is that you are on Windows. What Python version do you have? For Windows, we have cython modules for Python 3.5 only (Linux we have for 3.5 and 3.6).

**Comment by alexberd** [comment]
> 
> 
> You mentioned that you added 'my-path/Examples/Image/Detection/'. Did you try adding Examples/Image/Detection/utils/cython_modules?
> 
> Also, what's your platform and Python version? We have pre-built modules for Python 3.5 for Windows and for Python 3.4, 3.5, 3.6 for Linux. If you specs are different, then you will have to build these modules yourself.

Would it be possible to furth erillustrate how to build those modules for python 3.6?
